import arcanist from "../../../packages/data/src/classes/arcanist.json";
import barbarian from "../../../packages/data/src/classes/barbarian.json";
import fighter from "../../../packages/data/src/classes/fighter.json";
import rogue from "../../../packages/data/src/classes/rogue.json";
import human from "../../../packages/data/src/races/human.json";
import combatCasting from "../../../packages/data/src/feats/combat-casting.json";
import powerAttack from "../../../packages/data/src/feats/power-attack.json";
import exploits from "../../../packages/data/src/options/arcanist-exploits.json";
import ragePowers from "../../../packages/data/src/options/rage-powers.json";
import rogueTalents from "../../../packages/data/src/options/rogue-talents.json";
import mageArmor from "../../../packages/data/src/spells/mage-armor.json";
import magicMissile from "../../../packages/data/src/spells/magic-missile.json";
import shield from "../../../packages/data/src/spells/shield.json";
import detectMagic from "../../../packages/data/src/spells/detect-magic.json";
import light from "../../../packages/data/src/spells/light.json";
import mageHand from "../../../packages/data/src/spells/mage-hand.json";
import rayOfFrost from "../../../packages/data/src/spells/ray-of-frost.json";
import readMagic from "../../../packages/data/src/spells/read-magic.json";
import alarm from "../../../packages/data/src/spells/alarm.json";
import charmPerson from "../../../packages/data/src/spells/charm-person.json";
import colorSpray from "../../../packages/data/src/spells/color-spray.json";
import holdPortal from "../../../packages/data/src/spells/hold-portal.json";
import sleep from "../../../packages/data/src/spells/sleep.json";
import arcanistSpellCatalogue from "../../../packages/data/src/spell-catalogues/arcanist-levels-2-9.json";

export const classes = [arcanist, barbarian, fighter, rogue];
export { human };
export const feats = [combatCasting, powerAttack];
export const optionGroups = [exploits, ragePowers, rogueTalents];
export const spells = [detectMagic, light, mageHand, rayOfFrost, readMagic, alarm, charmPerson, colorSpray, holdPortal, mageArmor, magicMissile, shield, sleep, ...arcanistSpellCatalogue.spells];
export const skills = [{name:"Acrobatics",ability:"dexterity"},{name:"Climb",ability:"strength"},{name:"Diplomacy",ability:"charisma"},{name:"Knowledge (arcana)",ability:"intelligence"},{name:"Perception",ability:"wisdom"},{name:"Spellcraft",ability:"intelligence"},{name:"Stealth",ability:"dexterity"}] as const;
