import arcanist from "../../../packages/data/src/classes/arcanist.json";
import barbarian from "../../../packages/data/src/classes/barbarian.json";
import fighter from "../../../packages/data/src/classes/fighter.json";
import rogue from "../../../packages/data/src/classes/rogue.json";
import human from "../../../packages/data/src/races/human.json";
import dwarf from "../../../packages/data/src/races/dwarf.json";
import elf from "../../../packages/data/src/races/elf.json";
import gnome from "../../../packages/data/src/races/gnome.json";
import halfElf from "../../../packages/data/src/races/half-elf.json";
import halfling from "../../../packages/data/src/races/halfling.json";
import halfOrc from "../../../packages/data/src/races/half-orc.json";
import combatCasting from "../../../packages/data/src/feats/combat-casting.json";
import powerAttack from "../../../packages/data/src/feats/power-attack.json";
import cleave from "../../../packages/data/src/feats/cleave.json";
import combatExpertise from "../../../packages/data/src/feats/combat-expertise.json";
import dodge from "../../../packages/data/src/feats/dodge.json";
import greatFortitude from "../../../packages/data/src/feats/great-fortitude.json";
import improvedInitiative from "../../../packages/data/src/feats/improved-initiative.json";
import improvedUnarmedStrike from "../../../packages/data/src/feats/improved-unarmed-strike.json";
import ironWill from "../../../packages/data/src/feats/iron-will.json";
import lightningReflexes from "../../../packages/data/src/feats/lightning-reflexes.json";
import pointBlankShot from "../../../packages/data/src/feats/point-blank-shot.json";
import preciseShot from "../../../packages/data/src/feats/precise-shot.json";
import rapidShot from "../../../packages/data/src/feats/rapid-shot.json";
import toughness from "../../../packages/data/src/feats/toughness.json";
import weaponFinesse from "../../../packages/data/src/feats/weapon-finesse.json";
import exploits from "../../../packages/data/src/options/arcanist-exploits.json";
import ragePowers from "../../../packages/data/src/options/rage-powers.json";
import rogueTalents from "../../../packages/data/src/options/rogue-talents.json";
import combatFeats from "../../../packages/data/src/options/combat-feats.json";
import fighterWeaponGroups from "../../../packages/data/src/options/fighter-weapon-groups.json";
import mageArmor from "../../../packages/data/src/spells/mage-armor.json";
import magicMissile from "../../../packages/data/src/spells/magic-missile.json";
import shield from "../../../packages/data/src/spells/shield.json";
import detectMagic from "../../../packages/data/src/spells/detect-magic.json";
import light from "../../../packages/data/src/spells/light.json";
import mageHand from "../../../packages/data/src/spells/mage-hand.json";
import rayOfFrost from "../../../packages/data/src/spells/ray-of-frost.json";
import readMagic from "../../../packages/data/src/spells/read-magic.json";
import alarm from "../../../packages/data/src/spells/alarm.json";
import charmPerson from "../../../packages/data/src/spells/charm-person.json";
import colorSpray from "../../../packages/data/src/spells/color-spray.json";
import holdPortal from "../../../packages/data/src/spells/hold-portal.json";
import sleep from "../../../packages/data/src/spells/sleep.json";
import arcanistSpellCatalogue from "../../../packages/data/src/spell-catalogues/arcanist-levels-2-9.json";
import arcanistStarterSpellCatalogue from "../../../packages/data/src/spell-catalogues/arcanist-levels-0-1.json";

export const classes = [arcanist, barbarian, fighter, rogue];
export const ancestries = [human, dwarf, elf, gnome, halfElf, halfling, halfOrc];
export const feats = [combatCasting, powerAttack, cleave, combatExpertise, dodge, greatFortitude, improvedInitiative, improvedUnarmedStrike, ironWill, lightningReflexes, pointBlankShot, preciseShot, rapidShot, toughness, weaponFinesse];
export const optionGroups = [exploits, ragePowers, rogueTalents, combatFeats, fighterWeaponGroups];
export const spells = [detectMagic, light, mageHand, rayOfFrost, readMagic, alarm, charmPerson, colorSpray, holdPortal, mageArmor, magicMissile, shield, sleep, ...arcanistStarterSpellCatalogue.spells, ...arcanistSpellCatalogue.spells];
export const skills = [{name:"Acrobatics",ability:"dexterity"},{name:"Climb",ability:"strength"},{name:"Diplomacy",ability:"charisma"},{name:"Knowledge (arcana)",ability:"intelligence"},{name:"Perception",ability:"wisdom"},{name:"Spellcraft",ability:"intelligence"},{name:"Stealth",ability:"dexterity"}] as const;
