name: Validate PF1e data
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Check
        shell: bash
        run: |
          set -o pipefail
          npm run check 2>&1 | tee check.log
      - name: Upload check failure log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-failure-log
          path: check.log
      - run: npm run build
